### ISSUE TITLE
Multiple color values not outputting.

### ISSUE THREAD

**Issue by bzerangue** [riasvdv/statamic-color-swatches#3]
I am using Statamic 2.11.14. 

I have installed the Color Swatches add-on for Statamic. It works for individual color definitions, but for multiple colors, it doesn't seem to work.

```yaml
footer_color:
  type: color_swatches
  display: 'Footer Color'
  show_when:
    add_footer: true
  colors:
    defaultBlue:
      - '#bcd1df'
      - '#386688'
      - '#ffffff'
    darkGray:
      - '#999999'
      - '#222222'
      - '#fefefe'
  default:
    - '#bcd1df'
    - '#386688'
    - '#ffffff'
```

When I try to output values after selecting the darkGray option...

```handlebars
<h1>{{ footer_color.label }} {{ footer_color.value[1] }}</h1>
```

It outputs...

```handlebars
<h1>darkGray {{ footer_color.value[1] }}</h1>
```

Is there a reason why this isn't outputting the color value of `#222222` which is the one it should be outputting?
