### ISSUE TITLE
Value initially not being saved as an array

### ISSUE THREAD

**Issue by robdekort** [riasvdv/statamic-color-swatches#40]
I have the swatches field in my page blueprint and its configured like this:

```yaml
-
  handle: theme
  field:
    colors:
      -
        label: 'Blue'
        value: 'rgb(44 103 153)'
      -
        label: 'Green'
        value: 'rgb(79 124 74)'
      -
        ...
```

On the initial save the value gets saved like this:

```yaml
theme:
  label: Blue
  value: 'rgb(44 103 153)'
```

After switching colors and resaving the value gets saved like this:

```yaml
theme:
  label: Blue
  value:
    - 'rgb(44 103 153)'
```

In my templates I'm expecting an array so the initial saves causes an error:

```
array_key_exists(): Argument #2 ($array) must be of type array, string given
```
