### ISSUE TITLE
Multiple colors don't get saved as an array

### ISSUE THREAD

**Issue by robdekort** [riasvdv/statamic-color-swatches#43]
Not sure how this happened but I found my color swatch saved like this:

```yaml
theme:
  label: Blue
  value:
    - 'rgb(44 103 153)', 'rgb(224 255 255)'
```

instead of:

```yaml
theme:
  label: Blue
  value:
    - 'rgb(44 103 153)',
    - 'rgb(224 255 255)'
```

Reselecting the theme in the CP and re-saving the entry fixes it. 

- Blueprint: [blueprint.zip](https://github.com/riasvdv/statamic-color-swatches/files/9991692/blueprint.zip)
- Imported field(s): [imported-fieldset.zip](https://github.com/riasvdv/statamic-color-swatches/files/9991694/imported-fieldset.zip)
