### ISSUE TITLE
Default value causes state to be dirty when the field is not visible.

### ISSUE THREAD

**Issue by lauritsen** [riasvdv/statamic-color-swatches#53]
I have an issue with getting the unsaved changes prompt when I didn't change anything on a page. It seems to me to be related to having default values specified for a color_swatches field, that are not currently visible because of a condition. My assumption is that somehow when loading the page, that default value is being set, even if the field is not visible, causing the state to be dirty. 

Steps to reproduce

1. Install statamic
2. Install color-swatches
3. Add color-swatches to the pages blueprint see config below
4. Add a page with the title Bug
5. Save and publish both the Home page and the new Bug page
6. Navigate to each page and back without making changes
7. From the Bug page you will get the unsaved changes prompt, but not from the Home page where the color swatches is visible

```
-
  handle: color_swatches_field
  field:
    colors:
      -
        id: ll5apb3i
        label: Red
        value:
          - '#f70707'
      -
        id: ll5ars70
        label: Black
        value:
          - '#000000'
    default: Red
    type: color_swatches
    display: 'Color Swatches Field'
    icon: color
    listable: hidden
    instructions_position: above
    visibility: visible
    hide_display: false
    unless:
      title: 'equals Bug'
```
